In [1]:
import pandas as pd
import numpy as np
import datetime

from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv('kickstarter.csv')
data.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

In [3]:
len(data)

378661

In [4]:
# Start-up outcomes categories
print('Outcome: ', list(data['state'].unique()))

Outcome:  ['failed', 'canceled', 'successful', 'live', 'undefined', 'suspended']

In [5]:
live = np.where(data.state == 'live')[0]

print('The indeces: ', live)

The indeces:  [    40    183    458 ... 378429 378496 378512]

In [6]:
data.iloc[live]

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
40,1000149007,Unschooling To University Book Project,Nonfiction,Publishing,CAD,2018-01-19,3000.0,2017-11-20 18:15:14,592.00,live,24,CA,185.65,472.88,2396.36
183,1000761521,KILOS.,Thrillers,Film & Video,USD,2018-02-06,5000.0,2017-12-23 20:34:31,310.00,live,4,US,200.00,310.00,5000.00
458,1002183790,The Man in the Field,Horror,Film & Video,GBP,2018-01-08,850.0,2017-12-21 11:19:18,413.00,live,11,GB,13.39,563.32,1159.38
537,1002599057,Dear Atlantas,Film & Video,Film & Video,USD,2018-02-16,2000.0,2017-12-18 02:48:27,5.00,live,1,US,5.00,5.00,2000.00
544,1002629894,Art Calendar 2018,Illustration,Art,MXN,2018-01-06,1000.0,2017-12-21 05:34:12,0.00,live,0,MX,0.00,0.00,52.32
627,100301082,"Feliz año nuevo, mamá.",Theater,Theater,MXN,2018-02-04,49000.0,2017-12-06 03:36:06,1000.00,live,2,MX,53.52,52.32,2563.83
641,1003104071,One GuitarMan Band,Music,Music,EUR,2018-01-17,2000.0,2017-12-18 00:02:46,0.00,live,0,IT,0.00,0.00,2427.39
752,1003665581,Durango Falls TV Show,Film & Video,Film & Video,USD,2018-01-20,10000.0,2017-11-21 10:56:11,1.00,live,1,US,0.00,1.00,10000.00
783,1003819770,GrandLo Café,Drinks,Food,USD,2018-01-19,25000.0,2017-11-20 19:54:51,9097.00,live,38,US,3438.00,9097.00,25000.00
842,100411349,E Coin Mining and Rig-Building Workshop,Hardware,Technology,USD,2018-01-06,3100.0,2017-11-22 20:28:28,225.00,live,9,US,75.00,225.00,3100.00
894,1004434782,DIY BOXCAT by Rato Kim - The Vinyl Art Toy Pla...,DIY,Crafts,USD,2018-01-06,2023.0,2017-12-04 17:26:58,3128.00,live,77,US,190.00,3128.00,2023.00
990,1005020458,Tiddly Trailer Bar Co.,Drinks,Food,USD,2018-01-02,9500.0,2017-11-03 21:36:22,9500.00,live,36,US,0.00,9500.00,9500.00
1427,1007266579,Pedal Whip Multitool,Hardware,Technology,USD,2018-01-05,1500.0,2017-12-06 19:20:22,464.00,live,6,US,0.00,464.00,1500.00
1502,1007700830,PHILE Magazine Issue No. 2 PRE-SALE,Art Books,Publishing,USD,2018-01-19,2500.0,2017-12-19 22:09:51,625.00,live,13,US,100.00,625.00,2500.00
1595,1008176449,Twenty-Six: Poetic Affirmations for Women,Art Books,Publishing,USD,2018-02-04,5700.0,2017-12-31 03:54:17,223.00,live,5,US,105.00,223.00,5700.00
1603,100822204,Freedom Ride Jacket | Revolutionizing Urban Cy...,Product Design,Design,USD,2018-01-20,20000.0,2017-11-21 15:02:31,55135.00,live,474,US,15459.00,55135.00,20000.00
1920,1009892892,MORE BIKE LIFE,Documentary,Film & Video,CAD,2018-02-01,23000.0,2017-12-18 17:37:37,0.00,live,0,CA,0.00,0.00,18372.07
2267,1011784198,Through the Eyes of My Mother,Photobooks,Photography,USD,2018-01-05,500.0,2017-12-29 23:15:36,349.00,live,7,US,274.00,349.00,500.00
2392,1012399283,"""The Woman in White""",Horror,Film & Video,USD,2018-01-27,1200.0,2017-12-16 19:50:55,429.00,live,13,US,35.00,429.00,1200.00
2594,101336613,I am Thankful,Publishing,Publishing,USD,2018-02-06,3500.0,2017-12-08 18:19:48,50.00,live,1,US,50.00,50.00,3500.00
2852,1014813411,YUMMA WEAR BY INTEGRESS INDUSTRIES INC. - ATHL...,Apparel,Fashion,CAD,2018-02-01,200000.0,2017-12-28 00:15:18,50.00,live,1,CA,39.32,39.94,159757.17
2856,101483724,The Advent Storybook,Children's Books,Publishing,USD,2018-01-04,18500.0,2017-12-04 13:32:13,7554.00,live,85,US,784.00,7554.00,18500.00
2892,1014982951,Freedom Through Art | Drawings That Inspire,Illustration,Art,USD,2018-01-06,300.0,2017-12-07 19:27:15,65.00,live,4,US,22.00,65.00,300.00
2982,1015409774,SpinBlock Table Tennis Center,Games,Games,USD,2018-01-28,15000.0,2017-12-29 03:35:45,2445.00,live,30,US,1810.00,2445.00,15000.00
3325,1017200721,Hacked at 17 - Teaching Teens Online Safety,Nonfiction,Publishing,USD,2018-01-16,20000.0,2017-11-22 12:11:36,1300.00,live,6,US,0.00,1300.00,20000.00
3338,1017252588,"My Debut EP - ""Shine!"" - PHASE 1",Pop,Music,USD,2018-01-09,5000.0,2017-12-10 22:44:19,5416.00,live,41,US,704.00,5416.00,5000.00
3996,1020564977,"AfterMarket Percussion Products, Inc. (AMPP, Inc)",Music,Music,USD,2018-01-14,19000.0,2017-11-30 16:19:17,851.00,live,14,US,0.00,851.00,19000.00
4039,1020721729,Edensoles | Sole To Soul Comfort with Dynamic ...,Product Design,Design,USD,2018-01-11,5000.0,2017-12-12 18:50:44,53099.00,live,962,US,1931.00,53099.00,5000.00
4055,1020847392,"Stop-A-Spill, The Coolest Way To Save Your Des...",Product Design,Design,USD,2018-01-05,125000.0,2017-12-06 11:17:44,0.00,live,0,US,0.00,0.00,125000.00
4134,1021242831,Plume: the Omnibus,Comics,Comics,USD,2018-01-12,25000.0,2017-12-11 16:00:02,43085.00,live,842,US,27118.00,43085.00,25000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374880,980522602,Steve's Story,Animation,Film & Video,EUR,2018-01-26,25000.0,2017-12-27 14:11:10,5.00,live,1,IT,0.00,6.07,30342.38
374904,980594622,"RESCUE MAC, IN10SE MINUTES",Tabletop Games,Games,USD,2018-01-22,680.0,2017-12-23 03:47:04,2025.00,live,75,US,642.00,2025.00,680.00
374927,980694521,Sexywear by Anna Elizabeth I,Apparel,Fashion,USD,2018-01-17,10000.0,2017-12-18 21:56:00,5.00,live,1,US,5.00,5.00,10000.00
375100,981610951,“Crocochain” - Skeleton Hand Crafted Multitool,Product Design,Design,USD,2018-01-11,1200.0,2017-12-12 23:12:42,249.00,live,2,US,498.00,249.00,1200.00
375195,982145967,Agnes' Front Lawn,Animation,Film & Video,USD,2018-01-18,3200.0,2017-12-19 03:56:33,1660.00,live,18,US,825.00,1660.00,3200.00
375244,982368556,Toddlr - Creating lasting friendships,Software,Technology,USD,2018-01-06,5000.0,2017-12-07 01:09:58,5.00,live,1,US,0.00,5.00,5000.00
375284,98257013,"The ""alley"" Reversible Solar BackPack",Product Design,Design,CHF,2018-01-20,25000.0,2017-12-06 17:14:44,9102.00,live,52,CH,2374.53,9372.30,25742.41
375395,983080290,Art in 365,Digital Art,Art,GBP,2018-01-12,20000.0,2017-12-13 23:04:07,130.00,live,4,GB,0.00,177.32,27279.55
375470,983530643,Pop-up store in Paris for 2018 spring collection.,Apparel,Fashion,EUR,2018-01-14,850.0,2017-11-15 18:18:13,403.00,live,13,FR,93.38,489.12,1031.64
375607,984297189,Major Arcana Tarot by A MIYAKO M,Illustration,Art,USD,2018-02-03,1000.0,2017-12-16 02:13:40,4125.00,live,94,US,2259.00,4125.00,1000.00
375660,984590245,Arrieros Somos,Web,Technology,MXN,2018-01-28,60000.0,2017-11-29 02:38:55,0.00,live,0,MX,0.00,0.00,3139.39
375883,985779919,Stop harassment. Be the change.,Apps,Technology,EUR,2018-01-03,9000.0,2017-11-04 09:25:49,5.00,live,1,ES,0.00,6.02,10840.50
376125,987063934,Leonardo da Vinci -Notebook Illustrations (Vol...,Art,Art,CAD,2018-01-26,600.0,2017-12-27 20:16:36,498.00,live,4,CA,144.70,397.80,479.27
376378,988360360,Molly Marrow- Debut EP 'Lead Me',Faith,Music,USD,2018-01-15,7000.0,2017-12-14 15:31:22,2949.00,live,41,US,1197.00,2949.00,7000.00
376479,988819801,"Gaz Bailey,s - Debut Album ""Folk It!"" With you...",Country & Folk,Music,GBP,2018-01-10,2000.0,2017-12-11 19:17:56,5.00,live,1,GB,0.00,6.82,2727.95
376594,989429327,ZOMBIE BINGO - Short student comedy-horror film,Comedy,Film & Video,GBP,2018-02-05,550.0,2017-12-10 21:25:10,230.00,live,3,GB,307.85,313.71,750.19
377042,991818171,Monsters and Kids,Tabletop Games,Games,SGD,2018-01-15,15000.0,2017-12-01 10:11:00,1282.00,live,39,SG,486.73,966.23,11305.40
377058,991937746,Find Me Game,Video Games,Games,USD,2018-01-19,20000.0,2017-11-20 21:36:12,426.00,live,15,US,39.00,426.00,20000.00
377108,992131825,THE GLOBALISTS,Events,Comics,USD,2018-01-21,2800.0,2017-11-24 21:55:13,1871.00,live,63,US,1196.00,1871.00,2800.00
377177,992522969,Personalized Crayon Banks,Crafts,Crafts,USD,2018-01-05,50000.0,2017-11-21 19:07:59,1.11,live,1,US,1.11,1.11,50000.00
377224,992761821,Vitamin Z: A Rock Opera about Mao Zedong,Pop,Music,USD,2018-01-27,7500.0,2017-12-28 17:18:52,450.00,live,8,US,90.00,450.00,7500.00
377265,992987490,Bicycle Neon Card - Save the night of old Hong...,Playing Cards,Games,HKD,2018-01-17,32000.0,2017-12-18 20:26:07,43573.00,live,85,HK,658.55,5569.00,4089.88
377325,993357594,Passionattire Mobile Boutique Brick and Motar,Fashion,Fashion,USD,2018-01-13,6500.0,2017-12-14 01:22:37,0.00,live,0,US,0.00,0.00,6500.00
377375,993591351,Boards & Brews - New Hampshire's First Board G...,Tabletop Games,Games,USD,2018-01-05,15000.0,2017-12-06 16:00:18,23397.00,live,140,US,11116.00,23397.00,15000.00
377419,99382576,Mini Figure Display Case,Product Design,Design,AUD,2018-01-18,67000.0,2017-12-19 04:41:30,863.00,live,24,AU,275.51,679.42,52747.60
377942,996530506,Linda: a film about finding love when you leas...,Drama,Film & Video,GBP,2018-01-25,1000.0,2017-12-26 17:04:29,720.00,live,16,GB,387.57,982.06,1363.98
378145,997562147,Yours Truly Short Film,Shorts,Film & Video,USD,2018-01-13,5800.0,2017-11-14 18:07:08,3500.00,live,39,US,990.00,3500.00,5800.00
378429,998848866,Sky & Signal EP!!!,Indie Rock,Music,USD,2018-01-13,1500.0,2017-11-14 00:13:10,1080.00,live,20,US,0.00,1080.00,1500.00
378496,999161903,Case with amplifier,Music,Music,MXN,2018-01-04,300000.0,2017-11-20 02:52:28,0.00,live,0,MX,0.00,0.00,15490.27
378512,999232064,Our little story - Discover Romania,World Music,Music,DKK,2018-01-19,186037.0,2017-12-05 11:11:01,1000.00,live,9,DK,143.57,162.94,30313.01

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 15 columns):
ID                  378661 non-null int64
name                378657 non-null object
category            378661 non-null object
main_category       378661 non-null object
currency            378661 non-null object
deadline            378661 non-null object
goal                378661 non-null float64
launched            378661 non-null object
pledged             378661 non-null float64
state               378661 non-null object
backers             378661 non-null int64
country             378661 non-null object
usd pledged         374864 non-null float64
usd_pledged_real    378661 non-null float64
usd_goal_real       378661 non-null float64
dtypes: float64(5), int64(2), object(8)
memory usage: 43.3+ MB

In [8]:
# Ati dropping the live projects...
data = data.query('state != "live"')

len(data)

375862

In [9]:
# Now all the indeces with live projects were eliminated
live = np.where(data.state == 'live')[0]

print('The indeces: ', live)

The indeces:  []

In [10]:
data.loc[live]

Empty DataFrame
Columns: [ID, name, category, main_category, currency, deadline, goal, launched, pledged, state, backers, country, usd pledged, usd_pledged_real, usd_goal_real]
Index: []

In [11]:
# Adding a new column for the outcome
# Assigning 'successful' == 1 and others == 0

data = data.assign(outcome=(data['state'] == 'successful').astype(int))

data.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,outcome
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,0
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,0
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,0
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,0
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,0

In [12]:
data.launched.dtype

dtype('O')

In [13]:
data[['launched']].head()

              launched
0  2015-08-11 12:12:28
1  2017-09-02 04:43:57
2  2013-01-12 00:20:50
3  2012-03-17 03:24:11
4  2015-07-04 08:35:03

In [14]:
# COnverting the launched col into datetime
data.launched = pd.to_datetime(data.launched, infer_datetime_format=True)

data.launched.dtype

dtype('<M8[ns]')

In [15]:
data.launched.head()

0   2015-08-11 12:12:28
1   2017-09-02 04:43:57
2   2013-01-12 00:20:50
3   2012-03-17 03:24:11
4   2015-07-04 08:35:03
Name: launched, dtype: datetime64[ns]

In [16]:
# After converting dates
# Creating new cols for day, hour, month and year
# Assigning the appropriate values from the launched col <timestamp>

data = data.assign(hour=data.launched.dt.hour,
                  day=data.launched.dt.day, 
                  month=data.launched.dt.month,
                  year=data.launched.dt.year)

data.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,outcome,hour,day,month,year
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,0,12,11,8,2015
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,0,4,2,9,2017
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,0,0,12,1,2013
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,0,3,17,3,2012
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,0,8,4,7,2015

In [17]:
cats = ['category', 'currency', 'country']

In [18]:
encoder = LabelEncoder()

In [19]:
enc_cats = data[cats].apply(encoder.fit_transform)

In [20]:
enc_cats.head()

   category  currency  country
0       108         5        9
1        93        13       22
2        93        13       22
3        90        13       22
4        55        13       22

In [21]:
X = data[['goal', 'hour', 'day', 'month', 'year', 'outcome']].join(enc_cats)
X.head()

      goal  hour  day  month  year  outcome  category  currency  country
0   1000.0    12   11      8  2015        0       108         5        9
1  30000.0     4    2      9  2017        0        93        13       22
2  45000.0     0   12      1  2013        0        93        13       22
3   5000.0     3   17      3  2012        0        90        13       22
4  19500.0     8    4      7  2015        0        55        13       22

In [22]:
# Creating training, validation and test sets

In [23]:
X.shape

(375862, 9)

In [24]:
valid_fraction = 0.1

valid_size = int(len(X) * valid_fraction)

valid_size

37586

In [25]:
X.shape

(375862, 9)

In [26]:
train = X[:-2* valid_size]

train.shape

(300690, 9)

In [27]:
valid = X[-2*valid_size:-valid_size]
valid.shape

(37586, 9)

In [28]:
test = X[-valid_size:]
test.shape

(37586, 9)

In [29]:
# Now train a model
import lightgbm as lgb
#using a LightGBM model. This is a tree-based model that typically provides the 
# Best performance, even compared to XGBoost. It's also relatively fast to train.

In [30]:
feature_cols = train.columns.drop('outcome')
feature_cols

Index(['goal', 'hour', 'day', 'month', 'year', 'category', 'currency',
       'country'],
      dtype='object')

In [31]:
dtrain = lgb.Dataset(train[feature_cols], label=train['outcome'])

dvalid = lgb.Dataset(valid[feature_cols], label=valid['outcome'])

In [32]:
param = {'num_leaves': 64, 'objective': 'binary'}
param['metric'] = 'auc'
num_round = 1000

bst = lgb.train(param, dtrain, num_round, valid_sets=[dvalid], early_stopping_rounds=5)

[LightGBM] [Info] Number of positive: 107340, number of negative: 193350
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012047 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 528
[LightGBM] [Info] Number of data points in the train set: 300690, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.356979 -> initscore=-0.588501
[LightGBM] [Info] Start training from score -0.588501
[1]	valid_0's auc: 0.694192
Training until validation scores don't improve for 5 rounds
[2]	valid_0's auc: 0.697026
[3]	valid_0's auc: 0.70002
[4]	valid_0's auc: 0.701645
[5]	valid_0's auc: 0.70601
[6]	valid_0's auc: 0.707926
[7]	valid_0's auc: 0.70945
[8]	valid_0's auc: 0.710437
[9]	valid_0's auc: 0.712047
[10]	valid_0's auc: 0.713417
[11]	valid_0's auc: 0.714648
[12]	valid_0's auc: 0.715791
[13]	valid_0's auc: 0.717431
[14]	valid_0's auc: 0.718216
[15]	valid_0's auc: 0.719381
[16]	valid_0's auc: 0.720884
[17]	valid_0's auc: 0.721617
[18]	valid_0's auc: 0.722788
[19]	valid_0's auc: 0.723305
[20]	valid_0's auc: 0.724826
[21]	valid_0's auc: 0.725596
[22]	valid_0's auc: 0.727436
[23]	valid_0's auc: 0.72788
[24]	valid_0's auc: 0.728838
[25]	valid_0's auc: 0.729249
[26]	valid_0's auc: 0.730276
[27]	valid_0's auc: 0.730651
[28]	valid_0's auc: 0.731264
[29]	valid_0's auc: 0.731584
[30]	valid_0's auc: 0.732643
[31]	valid_0's auc: 0.733118
[32]	valid_0's auc: 0.733422
[33]	valid_0's auc: 0.734007
[34]	valid_0's auc: 0.734475
[35]	valid_0's auc: 0.734652
[36]	valid_0's auc: 0.73488
[37]	valid_0's auc: 0.735944
[38]	valid_0's auc: 0.73617
[39]	valid_0's auc: 0.736498
[40]	valid_0's auc: 0.736767
[41]	valid_0's auc: 0.737663
[42]	valid_0's auc: 0.737783
[43]	valid_0's auc: 0.73798
[44]	valid_0's auc: 0.738213
[45]	valid_0's auc: 0.738784
[46]	valid_0's auc: 0.738881
[47]	valid_0's auc: 0.739012
[48]	valid_0's auc: 0.739203
[49]	valid_0's auc: 0.739353
[50]	valid_0's auc: 0.739844
[51]	valid_0's auc: 0.739929
[52]	valid_0's auc: 0.74008
[53]	valid_0's auc: 0.740276
[54]	valid_0's auc: 0.740519
[55]	valid_0's auc: 0.740655
[56]	valid_0's auc: 0.740712
[57]	valid_0's auc: 0.741008
[58]	valid_0's auc: 0.74109
[59]	valid_0's auc: 0.741133
[60]	valid_0's auc: 0.741264
[61]	valid_0's auc: 0.741467
[62]	valid_0's auc: 0.741628
[63]	valid_0's auc: 0.741912
[64]	valid_0's auc: 0.742196
[65]	valid_0's auc: 0.742252
[66]	valid_0's auc: 0.742332
[67]	valid_0's auc: 0.742413
[68]	valid_0's auc: 0.742516
[69]	valid_0's auc: 0.742732
[70]	valid_0's auc: 0.742774
[71]	valid_0's auc: 0.742838
[72]	valid_0's auc: 0.743004
[73]	valid_0's auc: 0.743035
[74]	valid_0's auc: 0.74308
[75]	valid_0's auc: 0.743136
[76]	valid_0's auc: 0.743692
[77]	valid_0's auc: 0.743737
[78]	valid_0's auc: 0.74382
[79]	valid_0's auc: 0.743885
[80]	valid_0's auc: 0.743901
[81]	valid_0's auc: 0.744103
[82]	valid_0's auc: 0.744096
[83]	valid_0's auc: 0.744116
[84]	valid_0's auc: 0.744169
[85]	valid_0's auc: 0.744238
[86]	valid_0's auc: 0.744322
[87]	valid_0's auc: 0.744317
[88]	valid_0's auc: 0.744377
[89]	valid_0's auc: 0.744429
[90]	valid_0's auc: 0.74449
[91]	valid_0's auc: 0.744508
[92]	valid_0's auc: 0.744506
[93]	valid_0's auc: 0.744536
[94]	valid_0's auc: 0.744573
[95]	valid_0's auc: 0.744585
[96]	valid_0's auc: 0.744584
[97]	valid_0's auc: 0.744695
[98]	valid_0's auc: 0.744693
[99]	valid_0's auc: 0.744694
[100]	valid_0's auc: 0.744673
[101]	valid_0's auc: 0.744673
[102]	valid_0's auc: 0.744711
[103]	valid_0's auc: 0.744707
[104]	valid_0's auc: 0.744769
[105]	valid_0's auc: 0.744816
[106]	valid_0's auc: 0.744817
[107]	valid_0's auc: 0.744803
[108]	valid_0's auc: 0.744816
[109]	valid_0's auc: 0.744857
[110]	valid_0's auc: 0.74515
[111]	valid_0's auc: 0.745133
[112]	valid_0's auc: 0.7451
[113]	valid_0's auc: 0.745123
[114]	valid_0's auc: 0.745126
[115]	valid_0's auc: 0.745099
Early stopping, best iteration is:
[110]	valid_0's auc: 0.74515

In [33]:
# Make predictions and evaluate the model
from sklearn import metrics

In [34]:
predictions = bst.predict(test[feature_cols])

In [35]:
score = metrics.roc_auc_score(test['outcome'], predictions)

print(f'Test AUC score: {score}')

Test AUC score: 0.7453069666284735